spring:
  datasource:
    url:  jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: jnr
    password: jnr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 8081
